linters:
  enable:
    - errcheck
    - errorlint
    - gci
    - misspell
    - revive
    - staticcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/vishvananda)

run:
  timeout: 5m
