issues:
  exclude-rules:
    - linters:
        - revive
      text: "don't use ALL_CAPS in Go names"

linters:
  enable:
    - errcheck
    - errorlint
    - gci
    - misspell
    - nonamedreturns
    - revive
    - staticcheck

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/vishvananda)

run:
  timeout: 5m
