name: gofumpt
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-cache: true
          args: --print-resources-usage --verbose --fix
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: 'fix golangci-lint'
